function edbudgethistoryS1 = importEdBudgetData(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  EDBUDGETHISTORYS1 = IMPORTFILE(FILE) reads data from the first
%  worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a table.
%
%  EDBUDGETHISTORYS1 = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  EDBUDGETHISTORYS1 = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  edbudgethistoryS1 = importfile("/Users/yuval/Development/Exploratory Data Analysis/US-Education-Spending/ed-budget-history.xlsx", "Sheet2", [2, 154]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 12-Aug-2020 21:22:15

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 154];
end

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 67);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":BO" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["VarName1", "inthousandsofdollars", "Var3", "Var4", "Var5", "Var6", "ESEATitleI", "ReadingFirst", "StrivingReaders", "HighSchoolIntervention", "ImpactAid", "ImprovingTeacherQualityStateGrants", "MathematicsandSciencePartnerships", "EducationalTechnologyStateGrants", "stCenturyCommunityLearningCenters", "StateAssessments", "IndianEducation", "TeacherIncentiveFund", "ChoiceIncentiveFund", "DrugPreventionEducation", "EnglishLanguageAcquisition", "SpecialEducation", "Careerandtechnicaleducation", "Other", "Var25", "TotalElementaryandSecondary", "Discretionary", "Mandatory", "Var29", "Var30", "FederalPellGrants", "FederalSupplementalEducationalOpportunityGrants", "FederalWorkStudy", "FederalPerkinsLoans", "FederalDirectStudentLoanProgram", "FederalFamilyEducationLoans", "AidforInstitutionalDevelopment", "FederalTRIOPrograms", "ScholarshipsandFellowships", "HowardUniversity", "Var41", "Other1", "Var43", "TotalPostsecondary", "Discretionary1", "Mandatory1", "Var47", "Var48", "RehabilitationServicesandDisabilityResearch", "AdultEducation", "EducationResearchandStatistics", "ResearchDevelopmentDisseminationandRegionalLaboratories", "Statistics", "Assessment", "ResearchandInnovationinSpecialEducation", "ProgramAdministrationAdministrationofCreditPrograms", "OfficeforCivilRights", "OfficeoftheInspectorGeneral", "Other3", "Var60", "TotalOther", "Discretionary2", "Mandatory2", "Var64", "TotalDepartmentofEducation", "TotalDiscretionary", "TotalMandatory"];
opts.SelectedVariableNames = ["VarName1", "inthousandsofdollars", "ESEATitleI", "ReadingFirst", "StrivingReaders", "HighSchoolIntervention", "ImpactAid", "ImprovingTeacherQualityStateGrants", "MathematicsandSciencePartnerships", "EducationalTechnologyStateGrants", "stCenturyCommunityLearningCenters", "StateAssessments", "IndianEducation", "TeacherIncentiveFund", "ChoiceIncentiveFund", "DrugPreventionEducation", "EnglishLanguageAcquisition", "SpecialEducation", "Careerandtechnicaleducation", "Other", "TotalElementaryandSecondary", "Discretionary", "Mandatory", "FederalPellGrants", "FederalSupplementalEducationalOpportunityGrants", "FederalWorkStudy", "FederalPerkinsLoans", "FederalDirectStudentLoanProgram", "FederalFamilyEducationLoans", "AidforInstitutionalDevelopment", "FederalTRIOPrograms", "ScholarshipsandFellowships", "HowardUniversity", "Other1", "TotalPostsecondary", "Discretionary1", "Mandatory1", "RehabilitationServicesandDisabilityResearch", "AdultEducation", "EducationResearchandStatistics", "ResearchDevelopmentDisseminationandRegionalLaboratories", "Statistics", "Assessment", "ResearchandInnovationinSpecialEducation", "ProgramAdministrationAdministrationofCreditPrograms", "OfficeforCivilRights", "OfficeoftheInspectorGeneral", "Other3", "TotalOther", "Discretionary2", "Mandatory2", "TotalDepartmentofEducation", "TotalDiscretionary", "TotalMandatory"];
opts.VariableTypes = ["double", "categorical", "char", "char", "char", "char", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "char", "double", "double", "double", "char", "char", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "char", "double", "char", "double", "double", "double", "char", "char", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "char", "double", "double", "double", "char", "double", "double", "double"];

% Specify file level properties
opts.ImportErrorRule = "omitrow";
opts.MissingRule = "omitrow";

% Specify variable properties
opts = setvaropts(opts, ["Var3", "Var4", "Var5", "Var6", "Var25", "Var29", "Var30", "Var41", "Var43", "Var47", "Var48", "Var60", "Var64"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["inthousandsofdollars", "Var3", "Var4", "Var5", "Var6", "Var25", "Var29", "Var30", "Var41", "Var43", "Var47", "Var48", "Var60", "Var64"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, ["VarName1", "ESEATitleI", "ReadingFirst", "StrivingReaders", "HighSchoolIntervention", "ImpactAid", "ImprovingTeacherQualityStateGrants", "MathematicsandSciencePartnerships", "EducationalTechnologyStateGrants", "stCenturyCommunityLearningCenters", "StateAssessments", "IndianEducation", "TeacherIncentiveFund", "ChoiceIncentiveFund", "DrugPreventionEducation", "EnglishLanguageAcquisition", "SpecialEducation", "Careerandtechnicaleducation", "Other", "TotalElementaryandSecondary", "Discretionary", "Mandatory", "FederalPellGrants", "FederalSupplementalEducationalOpportunityGrants", "FederalWorkStudy", "FederalPerkinsLoans", "FederalDirectStudentLoanProgram", "FederalFamilyEducationLoans", "AidforInstitutionalDevelopment", "FederalTRIOPrograms", "ScholarshipsandFellowships", "HowardUniversity", "Other1", "TotalPostsecondary", "Discretionary1", "Mandatory1", "RehabilitationServicesandDisabilityResearch", "AdultEducation", "EducationResearchandStatistics", "ResearchDevelopmentDisseminationandRegionalLaboratories", "Statistics", "Assessment", "ResearchandInnovationinSpecialEducation", "ProgramAdministrationAdministrationofCreditPrograms", "OfficeforCivilRights", "OfficeoftheInspectorGeneral", "Other3", "TotalOther", "Discretionary2", "Mandatory2", "TotalDepartmentofEducation", "TotalDiscretionary", "TotalMandatory"], "TreatAsMissing", '');

% Import the data
edbudgethistoryS1 = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":BO" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    edbudgethistoryS1 = [edbudgethistoryS1; tb]; %#ok<AGROW>
end

end